### PR TITLE
Error in the constructor for calling "this" object in the class.

### PR DESCRIPTION
**Pull request by adeelahmedcsku**
Add the below code of the constructor overloading is being used.
public Multiplication(int factorA,int factorB)
	{
		this.factorA=factorA;
		this.factorB=factorB;
		
	}

### CODE REVIEW

**Comment by adeelahmedcsku** [comment]
added the below code to remove the error in the book tutorial for the upcoming users.

**Comment by mechero** [comment]
Hi @adeelahmedcsku! Thanks for reading the book, I hope you're enjoying it.

Note that the constructor that you added _is already there_ because of this Lombok's annotation at the class level: `@RequiredArgsConstructor`. Lombok processes those annotations and injects that constructor.

What is probably happening is that your development environment has to be configured to "understand" Lombok and avoid showing you compilation errors. Which IDE are you using? There might be a Lombok plugin that you could use.

I hope it helps. Kind regards,
Moisés

**Comment by adeelahmedcsku** [comment]
Thanks for your kind response, Opps sorry then i am using eclipse sts and i have added the Lombok dependency in the pom.xml and also installed the lombok as described on the official site of lombok link you have given in the guide. i dont know what is going wrong with that. If i am missing any step kindly let me know thanks in advance

**Comment by adeelahmedcsku** [comment]
Ok great i configure the lombok correctly you was right dont need that constructor in it now.

**Comment by mechero** [comment]
Nice! I hope you enjoy the book.

**Pull request closed without merging**
